[package]
name = "z_lib"
version = "0.1.0"
authors = ["zhouwenxiang <zhouwx@lanxi.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
z_serde_yaml = { path = "z_serde_yaml" }